version: '3.8'
services:
  web:
    container_name: ssd_portfolio_cordmarston_com
    build:
      context: ./
      target: runner
    tty: true 
    stdin_open: true
    command: npm run start
    restart: always
    volumes:
      - .:/app
    ports:
      - "1718:1718"
    networks:
      - npmnetwork
networks:
  npmnetwork:
    external: true
    driver: bridge
