version: '3.8'
services:
  web:
    container_name: portfolio_cordmarston_com
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "1738:1738"
    restart: always
    environment:
      NODE_ENV: development
    networks:
      - npmnetwork
networks:
  npmnetwork:
    external: true
    driver: bridge
volumes:
  pgdata:
