version: '3.8'
services:
  web:
    container_name: portfolio_cordmarston_com
    build:
      context: ./
      target: runner
    tty: true 
    stdin_open: true
    command: npm run build
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    ports:
      - "1738:1738"
    networks:
      - npmnetwork
networks:
  npmnetwork:
    external: true
    driver: bridge
